[package]
name = "index-set"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = """
bitset implementation with support for atomic operations
"""
keywords = ["bitset", "data-structures"]

[dependencies]
